# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\Giftcher\widgets\MainWindow.ui'
#
# Created: Tue Feb 20 22:45:32 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 785)
        MainWindow.setMinimumSize(QtCore.QSize(643, 555))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_main = QtGui.QSplitter(self.centralwidget)
        self.splitter_main.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_main.setObjectName("splitter_main")
        self.layoutWidget = QtGui.QWidget(self.splitter_main)
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_fileops = QtGui.QVBoxLayout(self.layoutWidget)
        self.layout_fileops.setContentsMargins(0, 0, 0, 0)
        self.layout_fileops.setObjectName("layout_fileops")
        self.btn_input_folder = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_folder.sizePolicy().hasHeightForWidth())
        self.btn_input_folder.setSizePolicy(sizePolicy)
        self.btn_input_folder.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_input_folder.setObjectName("btn_input_folder")
        self.layout_fileops.addWidget(self.btn_input_folder)
        self.list_videoslist = QtGui.QListView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_videoslist.sizePolicy().hasHeightForWidth())
        self.list_videoslist.setSizePolicy(sizePolicy)
        self.list_videoslist.setMinimumSize(QtCore.QSize(42, 0))
        self.list_videoslist.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.list_videoslist.setObjectName("list_videoslist")
        self.layout_fileops.addWidget(self.list_videoslist)
        self.groupb_colortable = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupb_colortable.sizePolicy().hasHeightForWidth())
        self.groupb_colortable.setSizePolicy(sizePolicy)
        self.groupb_colortable.setObjectName("groupb_colortable")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupb_colortable)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dropdown_colortable = QtGui.QComboBox(self.groupb_colortable)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropdown_colortable.sizePolicy().hasHeightForWidth())
        self.dropdown_colortable.setSizePolicy(sizePolicy)
        self.dropdown_colortable.setObjectName("dropdown_colortable")
        self.verticalLayout_6.addWidget(self.dropdown_colortable)
        self.btn_import_act = QtGui.QPushButton(self.groupb_colortable)
        self.btn_import_act.setObjectName("btn_import_act")
        self.verticalLayout_6.addWidget(self.btn_import_act)
        self.layout_fileops.addWidget(self.groupb_colortable)
        self.btn_export = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setMinimumSize(QtCore.QSize(0, 49))
        self.btn_export.setObjectName("btn_export")
        self.layout_fileops.addWidget(self.btn_export)
        self.btn_clean = QtGui.QPushButton(self.layoutWidget)
        self.btn_clean.setEnabled(False)
        self.btn_clean.setMinimumSize(QtCore.QSize(0, 49))
        self.btn_clean.setObjectName("btn_clean")
        self.layout_fileops.addWidget(self.btn_clean)
        self.viewport_280 = Viewport(self.splitter_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewport_280.sizePolicy().hasHeightForWidth())
        self.viewport_280.setSizePolicy(sizePolicy)
        self.viewport_280.setMinimumSize(QtCore.QSize(0, 0))
        self.viewport_280.setObjectName("viewport_280")
        self.splitter_right = QtGui.QSplitter(self.splitter_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_right.sizePolicy().hasHeightForWidth())
        self.splitter_right.setSizePolicy(sizePolicy)
        self.splitter_right.setOrientation(QtCore.Qt.Vertical)
        self.splitter_right.setObjectName("splitter_right")
        self.layout_colortable = QtGui.QGroupBox(self.splitter_right)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout_colortable.sizePolicy().hasHeightForWidth())
        self.layout_colortable.setSizePolicy(sizePolicy)
        self.layout_colortable.setObjectName("layout_colortable")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layout_colortable)
        self.horizontalLayout_2.setContentsMargins(-1, 4, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plaintext_act_readout = QtGui.QPlainTextEdit(self.layout_colortable)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plaintext_act_readout.sizePolicy().hasHeightForWidth())
        self.plaintext_act_readout.setSizePolicy(sizePolicy)
        self.plaintext_act_readout.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.plaintext_act_readout.setObjectName("plaintext_act_readout")
        self.horizontalLayout_2.addWidget(self.plaintext_act_readout)
        self.viewport_136 = Viewport(self.splitter_right)
        self.viewport_136.setObjectName("viewport_136")
        self.horizontalLayout.addWidget(self.splitter_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChooseFolder = QtGui.QAction(MainWindow)
        self.actionChooseFolder.setObjectName("actionChooseFolder")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConfig = QtGui.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.actionDelete_temp_files = QtGui.QAction(MainWindow)
        self.actionDelete_temp_files.setObjectName("actionDelete_temp_files")
        self.actionShow_console = QtGui.QAction(MainWindow)
        self.actionShow_console.setObjectName("actionShow_console")
        self.actionmov2mp4 = QtGui.QAction(MainWindow)
        self.actionmov2mp4.setObjectName("actionmov2mp4")
        self.menuFile.addAction(self.actionChooseFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionConfig)
        self.menuOptions.addAction(self.actionDelete_temp_files)
        self.menuOptions.addAction(self.actionShow_console)
        self.menuOptions.addAction(self.actionmov2mp4)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_input_folder.setText(QtGui.QApplication.translate("MainWindow", "Select project folder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupb_colortable.setTitle(QtGui.QApplication.translate("MainWindow", "Color table (.act file)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_import_act.setText(QtGui.QApplication.translate("MainWindow", "Import act", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_export.setText(QtGui.QApplication.translate("MainWindow", "Export optimized GIFs", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clean.setText(QtGui.QApplication.translate("MainWindow", "Clean Project Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.layout_colortable.setTitle(QtGui.QApplication.translate("MainWindow", "Color table", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChooseFolder.setText(QtGui.QApplication.translate("MainWindow", "Choo&se project folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfig.setText(QtGui.QApplication.translate("MainWindow", "C&onfig", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_temp_files.setText(QtGui.QApplication.translate("MainWindow", "&Clean temp files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_console.setText(QtGui.QApplication.translate("MainWindow", "Show &console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionmov2mp4.setText(QtGui.QApplication.translate("MainWindow", "Convert &mov to mp4", None, QtGui.QApplication.UnicodeUTF8))

from widgets.viewport import Viewport
