# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets\Settings.ui'
#
# Created: Mon Feb 12 20:40:37 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dialog_settings(object):
    def setupUi(self, dialog_settings):
        dialog_settings.setObjectName("dialog_settings")
        dialog_settings.resize(293, 193)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_settings.sizePolicy().hasHeightForWidth())
        dialog_settings.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(dialog_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.console_enabled = QtGui.QCheckBox(dialog_settings)
        self.console_enabled.setText("")
        self.console_enabled.setObjectName("console_enabled")
        self.gridLayout.addWidget(self.console_enabled, 6, 1, 1, 2)
        self.label_console_enabled = QtGui.QLabel(dialog_settings)
        self.label_console_enabled.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_console_enabled.setObjectName("label_console_enabled")
        self.gridLayout.addWidget(self.label_console_enabled, 6, 0, 1, 1)
        self.label_default_folder = QtGui.QLabel(dialog_settings)
        self.label_default_folder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_default_folder.setObjectName("label_default_folder")
        self.gridLayout.addWidget(self.label_default_folder, 3, 0, 1, 1)
        self.label_damaged_filesize = QtGui.QLabel(dialog_settings)
        self.label_damaged_filesize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_damaged_filesize.setObjectName("label_damaged_filesize")
        self.gridLayout.addWidget(self.label_damaged_filesize, 1, 0, 1, 1)
        self.label_delimiter = QtGui.QLabel(dialog_settings)
        self.label_delimiter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_delimiter.setObjectName("label_delimiter")
        self.gridLayout.addWidget(self.label_delimiter, 4, 0, 1, 1)
        self.label_preload_files = QtGui.QLabel(dialog_settings)
        self.label_preload_files.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_preload_files.setObjectName("label_preload_files")
        self.gridLayout.addWidget(self.label_preload_files, 2, 0, 1, 1)
        self.label_level = QtGui.QLabel(dialog_settings)
        self.label_level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_level.setObjectName("label_level")
        self.gridLayout.addWidget(self.label_level, 5, 0, 1, 1)
        self.default_folder_browse = QtGui.QToolButton(dialog_settings)
        self.default_folder_browse.setObjectName("default_folder_browse")
        self.gridLayout.addWidget(self.default_folder_browse, 3, 2, 1, 1)
        self.logging_level = QtGui.QComboBox(dialog_settings)
        self.logging_level.setObjectName("logging_level")
        self.gridLayout.addWidget(self.logging_level, 5, 1, 1, 2)
        self.default_folder = QtGui.QLineEdit(dialog_settings)
        self.default_folder.setObjectName("default_folder")
        self.gridLayout.addWidget(self.default_folder, 3, 1, 1, 1)
        self.damaged_filesize = QtGui.QSpinBox(dialog_settings)
        self.damaged_filesize.setMaximum(1048576)
        self.damaged_filesize.setSingleStep(1)
        self.damaged_filesize.setObjectName("damaged_filesize")
        self.gridLayout.addWidget(self.damaged_filesize, 1, 1, 1, 2)
        self.preload_files = QtGui.QCheckBox(dialog_settings)
        self.preload_files.setText("")
        self.preload_files.setObjectName("preload_files")
        self.gridLayout.addWidget(self.preload_files, 2, 1, 1, 2)
        self.name_delimiter = QtGui.QLineEdit(dialog_settings)
        self.name_delimiter.setObjectName("name_delimiter")
        self.gridLayout.addWidget(self.name_delimiter, 4, 1, 1, 2)
        self.label_overwrite_gifs = QtGui.QLabel(dialog_settings)
        self.label_overwrite_gifs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_overwrite_gifs.setObjectName("label_overwrite_gifs")
        self.gridLayout.addWidget(self.label_overwrite_gifs, 7, 0, 1, 1)
        self.overwrite_gifs = QtGui.QCheckBox(dialog_settings)
        self.overwrite_gifs.setText("")
        self.overwrite_gifs.setObjectName("overwrite_gifs")
        self.gridLayout.addWidget(self.overwrite_gifs, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtGui.QDialogButtonBox(dialog_settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dialog_settings)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dialog_settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dialog_settings.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog_settings)

    def retranslateUi(self, dialog_settings):
        dialog_settings.setWindowTitle(QtGui.QApplication.translate("dialog_settings", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_console_enabled.setText(QtGui.QApplication.translate("dialog_settings", "Console enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_default_folder.setText(QtGui.QApplication.translate("dialog_settings", "Default folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_damaged_filesize.setText(QtGui.QApplication.translate("dialog_settings", "Damaged filesize (Kb)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_delimiter.setText(QtGui.QApplication.translate("dialog_settings", "Name delimiter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_preload_files.setText(QtGui.QApplication.translate("dialog_settings", "Preload files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_level.setText(QtGui.QApplication.translate("dialog_settings", "Logging level", None, QtGui.QApplication.UnicodeUTF8))
        self.default_folder_browse.setText(QtGui.QApplication.translate("dialog_settings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_overwrite_gifs.setText(QtGui.QApplication.translate("dialog_settings", "Overwrite Gifs", None, QtGui.QApplication.UnicodeUTF8))

