# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\Vault_Of_Gifs\widgets\viewport.ui'
#
# Created: Tue Feb 13 12:52:11 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(411, 540)
        self.main_layout = QtGui.QVBoxLayout(Form)
        self.main_layout.setSpacing(0)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.layout_viewport = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout_viewport.sizePolicy().hasHeightForWidth())
        self.layout_viewport.setSizePolicy(sizePolicy)
        self.layout_viewport.setMinimumSize(QtCore.QSize(0, 0))
        self.layout_viewport.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.layout_viewport.setObjectName("layout_viewport")
        self.verticalLayout = QtGui.QVBoxLayout(self.layout_viewport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = Viewer(self.layout_viewport)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.line = QtGui.QFrame(self.layout_viewport)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.layout_playback = QtGui.QHBoxLayout()
        self.layout_playback.setObjectName("layout_playback")
        self.btn_fb = QtGui.QPushButton(self.layout_viewport)
        self.btn_fb.setEnabled(False)
        self.btn_fb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.btn_fb.setFont(font)
        self.btn_fb.setObjectName("btn_fb")
        self.layout_playback.addWidget(self.btn_fb)
        self.btn_playpause = QtGui.QPushButton(self.layout_viewport)
        self.btn_playpause.setEnabled(False)
        self.btn_playpause.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.btn_playpause.setFont(font)
        self.btn_playpause.setCheckable(True)
        self.btn_playpause.setObjectName("btn_playpause")
        self.layout_playback.addWidget(self.btn_playpause)
        self.btn_ff = QtGui.QPushButton(self.layout_viewport)
        self.btn_ff.setEnabled(False)
        self.btn_ff.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.btn_ff.setFont(font)
        self.btn_ff.setObjectName("btn_ff")
        self.layout_playback.addWidget(self.btn_ff)
        self.verticalLayout.addLayout(self.layout_playback)
        self.layout_speed = QtGui.QHBoxLayout()
        self.layout_speed.setContentsMargins(-1, 0, -1, -1)
        self.layout_speed.setObjectName("layout_speed")
        self.lbl_speed = QtGui.QLabel(self.layout_viewport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_speed.sizePolicy().hasHeightForWidth())
        self.lbl_speed.setSizePolicy(sizePolicy)
        self.lbl_speed.setMinimumSize(QtCore.QSize(30, 0))
        self.lbl_speed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_speed.setAutoFillBackground(False)
        self.lbl_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_speed.setObjectName("lbl_speed")
        self.layout_speed.addWidget(self.lbl_speed)
        self.spin_speed = QtGui.QDoubleSpinBox(self.layout_viewport)
        self.spin_speed.setWrapping(False)
        self.spin_speed.setFrame(True)
        self.spin_speed.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spin_speed.setMinimum(0.1)
        self.spin_speed.setMaximum(4.0)
        self.spin_speed.setSingleStep(0.01)
        self.spin_speed.setProperty("value", 1.0)
        self.spin_speed.setObjectName("spin_speed")
        self.layout_speed.addWidget(self.spin_speed)
        self.slider_speed = QtGui.QSlider(self.layout_viewport)
        self.slider_speed.setMinimum(10)
        self.slider_speed.setMaximum(400)
        self.slider_speed.setSingleStep(1)
        self.slider_speed.setProperty("value", 100)
        self.slider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_speed.setInvertedAppearance(False)
        self.slider_speed.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_speed.setObjectName("slider_speed")
        self.layout_speed.addWidget(self.slider_speed)
        self.verticalLayout.addLayout(self.layout_speed)
        self.layout_quality = QtGui.QHBoxLayout()
        self.layout_quality.setObjectName("layout_quality")
        self.lbl_quality = QtGui.QLabel(self.layout_viewport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_quality.sizePolicy().hasHeightForWidth())
        self.lbl_quality.setSizePolicy(sizePolicy)
        self.lbl_quality.setMinimumSize(QtCore.QSize(30, 0))
        self.lbl_quality.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_quality.setFrameShadow(QtGui.QFrame.Plain)
        self.lbl_quality.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_quality.setObjectName("lbl_quality")
        self.layout_quality.addWidget(self.lbl_quality)
        self.spin_quality = QtGui.QSpinBox(self.layout_viewport)
        self.spin_quality.setMaximum(1024)
        self.spin_quality.setObjectName("spin_quality")
        self.layout_quality.addWidget(self.spin_quality)
        self.slider_quality = QtGui.QSlider(self.layout_viewport)
        self.slider_quality.setMaximum(400)
        self.slider_quality.setPageStep(20)
        self.slider_quality.setOrientation(QtCore.Qt.Horizontal)
        self.slider_quality.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_quality.setTickInterval(20)
        self.slider_quality.setObjectName("slider_quality")
        self.layout_quality.addWidget(self.slider_quality)
        self.verticalLayout.addLayout(self.layout_quality)
        self.btn_update = QtGui.QPushButton(self.layout_viewport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update.sizePolicy().hasHeightForWidth())
        self.btn_update.setSizePolicy(sizePolicy)
        self.btn_update.setObjectName("btn_update")
        self.verticalLayout.addWidget(self.btn_update)
        self.check_livepreview = QtGui.QCheckBox(self.layout_viewport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_livepreview.sizePolicy().hasHeightForWidth())
        self.check_livepreview.setSizePolicy(sizePolicy)
        self.check_livepreview.setObjectName("check_livepreview")
        self.verticalLayout.addWidget(self.check_livepreview)
        self.main_layout.addWidget(self.layout_viewport)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.layout_viewport.setTitle(QtGui.QApplication.translate("Form", "_x_ px", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fb.setText(QtGui.QApplication.translate("Form", "", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_playpause.setText(QtGui.QApplication.translate("Form", "⏵/⏸", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ff.setText(QtGui.QApplication.translate("Form", "", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_speed.setText(QtGui.QApplication.translate("Form", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_quality.setText(QtGui.QApplication.translate("Form", "Lossy", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_update.setText(QtGui.QApplication.translate("Form", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.check_livepreview.setText(QtGui.QApplication.translate("Form", "Auto update", None, QtGui.QApplication.UnicodeUTF8))

from widgets.viewport_viewer import Viewer
